services:
  ubuntu:
    build:
      context: ..
      dockerfile: docker/ubuntu.Dockerfile
    container_name: dotfiles-test-ubuntu

  fedora:
    build:
      context: ..
      dockerfile: docker/fedora.Dockerfile
    container_name: dotfiles-test-fedora

  arch:
    build:
      context: ..
      dockerfile: docker/arch.Dockerfile
    container_name: dotfiles-test-arch
